### ISSUE TITLE
DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL'

### ISSUE THREAD

**Issue by leer5** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client#2]
Hello

I followed the tutorial and generated client side POJOs from my schema. However, when I create a simple  request to query a GraphQL server, I get the following:

Field graphQL in graphql.spring.web.servlet.components.DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'graphql.GraphQL' in your configuration.

Process finished with exit code 0

Any advice on how to fix this?

Thanks
Robert
![2020-09-29_8-59-06](https://user-images.githubusercontent.com/52473039/94583311-265a3b00-0232-11eb-9906-93b6e0709a61.png)

**Comment by etienne-sf** [comment]
Hello,

  I'm sorry. I hadn't activate the github notifications, and discoverer your message only now.

Did you solve this issue ?


The provided code works. But I may have missed something in the explanation.
I'll check that.
