### ISSUE TITLE
Hardcoded object response values required in request rather than being able to use select columns generated from schema 

### ISSUE THREAD

**Issue by AndyCa** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client#5]
Schema:

```  """
  fetch data from the table: "portfolio"
  """
  portfolio(
    """distinct select on columns"""
    distinct_on: [portfolio_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [portfolio_order_by!]

    """filter the rows returned"""
    where: portfolio_bool_exp
  ): [portfolio!]!
```

The mvn graphql:generateClientCode generates values from my schema that can be used as return values from queries like the following:

`@GraphQLEnumType("portfolio_select_column")
public enum portfolio_select_column {
	id, name;
}
`

However when defining my query I have to hardcode the return values rather than being able to build my return values like I can for almost all other parts of the query:

```		
	private GraphQLRequest portfoliosRequest;

        portfoliosRequest = queryExecutor
				.getPortfolioGraphQLRequest(String.format("{id name}"));<------------- magic strings
```

```	public List<org.forum.client.portfolio> portfolios() throws GraphQLRequestExecutionException {
		return queryExecutor.portfolio(
				this.portfoliosRequest,  <------------ object response (why can't I specify enums?)
				Collections.singletonList(portfolio_select_column.id),  <-------- distinct_on param however does allow me to build with the enums
				null,
				0,
				Collections.emptyList(),
				portfolio_bool_exp.builder().build()
				);
	}
```
I can reference the enums in the portfolioRequest object response and String.format them but I'm unclear why the select column enums that are autogenerated aren't intuitively added into the building of the query and appear to need to be hardcoded strings - especially when the `distinct_on` param uses the enums.

**Comment by etienne-sf** [comment]
Hello,

I'm not sure I understand the issue.

So here is what I undestood:
* The part of the GraphQL schema you copied is a field of the GraphQL Query type. 
* You prepare this request in your Java code, and store this prepared GraphQLRequest into the `portfoliosRequest ` variable


Just a detail: Why to you use `getPortfolioGraphQLRequest(String.format("{id name}"))`, `getPortfolioGraphQLRequest("{id name}");` should be enough


So my understanding is that you would like the query parameters to be in the prepared GraphQL request, instead of having to provid them at runtime, when calling `return queryExecutor.portfolio(...)`.
Is that correct ?

If yes, then take a look at the Full Request:

Prepare it this way:
```Java
portfoliosRequest = queryExecutor.getGraphQLRequest("query{portfolio:(distinct_on:[id]) {id name}}");
```

Then execute the query this way:

```Java
return queryExecutor.exec(portfoliosRequest).getPortofolio();
```

**Comment by AndyCa** [comment]
Hi,

I took another look today as I was sure I wasn't doing something right and I think I figured out what I wanted:

```
        org.forum.client.util.query_rootExecutor queryExecutor = new query_rootExecutor("http://localhost:8089/v1/graphql");

        com.graphql_java_generator.client.request.Builder builder = queryExecutor.getPortfolioResponseBuilder();
        com.graphql_java_generator.client.request.ObjectResponse request = builder.build();

        List<portfolio> portfolios = queryExecutor.portfolio(
                request,
                Collections.singletonList(portfolio_select_column.id),
                null,
                null,
                null,
                portfolio_bool_exp.builder().withId(Int_comparison_exp.builder().with_eq(1).build()).build()
        );
        logger.info("Portfolios read: {}", portfolios);

```

I couldn't understand why some of the request was being hardcoded as a string - but I guess that is the definition of a partial request or full request within your generated code. So what I wanted was the `Builder` object that is generated for my request and using that I can generate the query fully using the plugin generated POJOs. 

Thanks for you time again.
