### ISSUE TITLE
Code Not getting moved to define package

### ISSUE THREAD

**Issue by milindbangar79** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client#6]
Hi,

Thanks for the plugin. 

Plugin version --> 1.12.3

While following the guidelines , I updated the ```<packageName>``` with the one I want to generate the Client. 

Apparently the code is getting generated in ```target``` 

Am I missing anything?

Thanks
Milind

**Comment by etienne-sf** [comment]
There are two parameters:

´targetSourceFolder´ is to control in which folder the code is generated. 

´packageName´ is the name of the package that will contain the classes. 

This package will map to subfolders of ´targetSourceFolder´ 

Étienne

**Comment by poojajain2203** [comment]
Hi, I import the client project in my Eclipse workspace. /this showing multiple errors and Class are not found.

org.graphql_forum_sample.client.Application in this class QueryTypeExecutor is not founded. There are many such errors.

Did I missed something ?

**Comment by etienne-sf** [comment]
Please __start a new thread__, as your issue is probably different. 


You do a full maven build first, to generate the code : ´mvn clean install´ 

Étienne

**Comment by poojajain2203** [comment]
I already did the same.

**Comment by poojajain2203** [comment]
Hi,

I try to import GraphQL-Forum-Maven-Tutorial-client
<https://github.com/graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client>
project
alone, as well as with project graphql-maven-plugin-project
<https://github.com/graphql-java-generator/graphql-maven-plugin-project>

But in both cases, I am getting errors in the workspace.

Can you help by letting me know if both modules are dependent or
independent.

I need reference to create a client for GraphQL API's
