### ISSUE TITLE
Project import not working in Eclipse for Client import

### ISSUE THREAD

**Issue by poojajain2203** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client#7]
GraphQL-Forum-Maven-Tutorial-client After extracting jar for this project and import same in maven, I am getting Compilation issues.

**Comment by etienne-sf** [comment]
Did you execute the ´mvn clean install´ ?

(Possibly via the eclipse 'run as' command)

Étienne

**Comment by poojajain2203** [comment]
yes I did.. but still facing issues.

**Comment by poojajain2203** [comment]
I try to import GraphQL-Forum-Maven-Tutorial-client project alone, as well as with project graphql-maven-plugin-project

But in both cases, I am getting errors in the workspace.

Can you help by letting me know if both modules are dependent or independent.

I need reference to create a client for GraphQL API's

**Comment by poojajain2203** [comment]
Any updates ?

**Comment by etienne-sf** [comment]
Can you describe these errors ?

**Comment by poojajain2203** [comment]
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ GraphQL-Forum-Maven-Sample-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ GraphQL-Forum-Maven-Sample-client ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\Users\Pooja\Downloads\GraphQL-Forum-Maven-Tutorial-client-master\GraphQL-Forum-Maven-Tutorial-client-master\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.183 s
[INFO] Finished at: 2021-09-24T17:11:08+05:30
[INFO] Final Memory: 16M/188M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project GraphQL-Forum-Maven-Sample-client: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by poojajain2203** [comment]
> Can you describe these errors ?

Yes.. please find on above thread.

**Comment by etienne-sf** [comment]
There seems to be an issue with the version of your JDK.

The `--release` is only available since JDK 9. 
And to make sure that the plugin is compatible with Java 8, when compiling with earlier version of Java, this parameter is needed.

My guess is that you're using JDK 8 or older.

Can you switch to JDK 9 or latter ?

Etienne


NB: I'll add a _HowTo compile page_ on the wiki

**Comment by etienne-sf** [comment]
Oups !

 This is the tutorial project


Java 9 should not be necessary. 

I'll remove this wrong flag in a minute


(you'll still need Java 8 or latter)

**Comment by etienne-sf** [comment]
Hello,

I took more than one minute.

But I removed the flag. Can you update your local git, and re-test ?

Etienne

**Comment by poojajain2203** [comment]
Hi, Import of project gone perfect now... but to run a sample; I executed main method, and there is error as attached below.


java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:809)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.graphql_forum_sample.client.Main.main(Main.java:16)
Caused by: org.springframework.web.reactive.function.client.WebClientRequestException: Connection refused: no further information: localhost/127.0.0.1:8180; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:8180
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

Is there any Configurations need to change/update ?

**Comment by poojajain2203** [comment]
While clean compile install,


Getting build failure.

 Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
[ERROR] at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[ERROR] at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[ERROR] at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[ERROR] at java.lang.reflect.Field.set(Field.java:764)
[ERROR] at org.eclipse.sisu.bean.BeanPropertyField.set(BeanPropertyField.java:72)
[ERROR] at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
[ERROR] at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
[ERROR] at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
[ERROR] at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[ERROR] at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
[ERROR] at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
[ERROR] at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallb

**Comment by poojajain2203** [comment]
ANy Update for this ?

**Comment by etienne-sf** [comment]
Hello,

About the first error, `Connection refused: no further information: localhost/127.0.0.1:8180`. This is a client app that connect against a server.
If you don't start the server, the client can't connect to it. So you must build and start the server, prior to execute the client.
The relevant server is available in the [GraphQL-Forum-Maven-Tutorial-server](https://github.com/graphql-java-generator/GraphQL-Forum-Maven-Tutorial-server) github project.

About the second error, it's not clear for me about what you're doing:
* `clean compile install`, is it a `mvn clean install` ? I guess not, as the error is within `org.eclipse`
* Did you do a 'Run As/Maven build' in eclipse with these goals ? 
* Something else ?

Etienne

**Comment by poojajain2203** [comment]
I Run the server, at time of run as java application for Main class. I got connection Refuse error; but spring boot automatically up the server (Localhost). than why me getting connection refuse error.

**Comment by poojajain2203** [comment]
yes, second error I got when I use mvn clean compile install.

**Comment by poojajain2203** [comment]
Hi The Server project  **GraphQL-Forum-Maven-Tutorial-server** you mentioned has also import errors same as client project had, may be it's because of version issue.

Would you pls check and let inform for it.

**Comment by etienne-sf** [comment]
Yes, right

I just finished correcting an issue with the Gradle plug-in.  

I'll correct this today

**Comment by etienne-sf** [comment]
It's now corrected. 

Can you confirm that?
