### ISSUE TITLE
graphql-java-runtime 1.18.6 is not available in Maven central

### ISSUE THREAD

**Issue by vitalii-chura-axon** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client#8]
The latest available version is 1.18. I checked here https://repo.maven.apache.org/maven2/com/graphql-java-generator/graphql-java-runtime/ and here https://search.maven.org/artifact/com.graphql-java-generator/graphql-java-runtime

Could you please advice if the latest version was uploaded to Maven repo?

**Comment by etienne-sf** [comment]
Hello,

This component has been removed, to be split between the client and the server runtime. 

Please check this link instead : 

https://mvnrepository.com/artifact/com.graphql-java-generator/graphql-java-client-dependencies

Étienne
